version: '3.0'

services:
  app:
    build:
      context: .
    command: bash start.sh
    ports:
      - "8080-8080"
      - "5005-5005"
    environment:
      GRADLE_USER_HOME: /box
    volumes:
      - ..:/flash-cards
      - box:box
    depends_on:
      - db
  db:
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: flash-cards
      MONGO_INITDB_ROOT_PASSWORD: flash-cards
      MONGO_INITDB_DATABASE: flash-cards
    ports:
      - "27017:27017"
  box:
    image: busybox
    volumes:
      - /box
volumes:
  db:
  box: